require('dotenv').config();
const { Resend } = require('resend');
const logger = require('./logger');

const resend = new Resend(process.env.RESEND_API_KEY);
const fromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';

// DEPRECATED: Review gating removed - negative feedback alerts no longer sent
// Kept for backwards compatibility, but not used in new flow
const sendNegativeFeedbackAlert = async (tenantEmail, customerName, rating, comment, phone) => {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error('Resend API key not configured');
    }

    const subject = `⚠️ URGENT: New ${rating}-Star Review from ${customerName}`;

    const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #dc2626 0%, #991b1b 100%);
      color: white;
      padding: 30px;
      border-radius: 10px 10px 0 0;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
    }
    .content {
      background: #ffffff;
      border: 2px solid #fee2e2;
      border-top: none;
      padding: 30px;
      border-radius: 0 0 10px 10px;
    }
    .alert-box {
      background: #fef2f2;
      border-left: 4px solid #dc2626;
      padding: 15px;
      margin: 20px 0;
    }
    .customer-info {
      background: #f9fafb;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
    }
    .info-row {
      display: flex;
      margin: 10px 0;
      padding: 10px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .info-row:last-child {
      border-bottom: none;
    }
    .info-label {
      font-weight: 600;
      color: #6b7280;
      min-width: 120px;
    }
    .info-value {
      color: #111827;
    }
    .stars {
      color: #fbbf24;
      font-size: 24px;
      margin: 10px 0;
    }
    .feedback {
      background: #ffffff;
      border: 1px solid #e5e7eb;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
      font-style: italic;
    }
    .cta-button {
      display: inline-block;
      background: #dc2626;
      color: white;
      padding: 15px 30px;
      text-decoration: none;
      border-radius: 8px;
      font-weight: 600;
      margin: 20px 0;
    }
    .footer {
      text-align: center;
      color: #6b7280;
      font-size: 14px;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>⚠️ URGENT: Negative Review Alert</h1>
  </div>

  <div class="content">
    <div class="alert-box">
      <strong>Action Required:</strong> A customer just left a ${rating}-star review.
      This feedback has been captured privately and was NOT posted publicly.
    </div>

    <div class="customer-info">
      <h2 style="margin-top: 0; color: #111827;">Customer Details</h2>

      <div class="info-row">
        <span class="info-label">Name:</span>
        <span class="info-value"><strong>${customerName || 'Anonymous'}</strong></span>
      </div>

      <div class="info-row">
        <span class="info-label">Phone:</span>
        <span class="info-value"><strong><a href="tel:${phone}">${phone}</a></strong></span>
      </div>

      <div class="info-row">
        <span class="info-label">Rating:</span>
        <span class="stars">${'★'.repeat(rating)}${'☆'.repeat(5 - rating)}</span>
      </div>
    </div>

    <h3 style="color: #111827;">Their Feedback:</h3>
    <div class="feedback">
      "${comment}"
    </div>

    <div style="text-align: center;">
      <a href="tel:${phone}" class="cta-button">
        📞 Call ${customerName} Now
      </a>
    </div>

    <div class="alert-box">
      <strong>💡 Recommended Action:</strong> Call this customer within 24 hours to address their concerns.
      Turning a negative experience into a positive one can create a loyal customer.
    </div>
  </div>

  <div class="footer">
    <p>This alert was generated by FilterFive</p>
    <p>The customer's review was captured privately and will not appear on public platforms.</p>
  </div>
</body>
</html>
    `;

    const result = await resend.emails.send({
      from: fromEmail,
      to: tenantEmail,
      subject: subject,
      html: htmlBody
    });

    // Debug: Log full result structure
    console.log('Resend API Response:', JSON.stringify(result, null, 2));

    // Check for errors in response
    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message} (Status: ${result.error.statusCode})`);
    }

    // Extract email ID from response
    const emailId = result?.data?.id || result?.id;

    if (!emailId) {
      throw new Error('No email ID returned from Resend API');
    }

    console.log(`✓ Negative feedback alert sent to ${tenantEmail} - Email ID: ${emailId}`);

    return {
      success: true,
      emailId: emailId
    };

  } catch (error) {
    console.error('✗ Resend email sending failed:', error.message);
    throw error;
  }
};

/**
 * Send Email Verification
 */
const sendVerificationEmail = async (email, businessName, verificationToken) => {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error('Resend API key not configured');
    }

    const templates = require('./emailTemplates');
    const verificationUrl = `${process.env.APP_URL}/verify/${verificationToken}`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Verify your MoreStars account',
      html: templates.verificationEmail(businessName, verificationUrl)
    });

    if (result.error) {
      logger.error('Verification email failed', { email, error: result.error.message });
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Verification email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Verification email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Welcome Email (After verification)
 */
const sendWelcomeEmail = async (email, businessName) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Welcome to MoreStars - Your trial has started!',
      html: templates.welcomeEmail(businessName, dashboardUrl)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Welcome email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Welcome email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Password Reset Email
 */
const sendPasswordResetEmail = async (email, businessName, resetToken) => {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error('Resend API key not configured');
    }

    const templates = require('./emailTemplates');
    const resetUrl = `${process.env.APP_URL}/reset-password/${resetToken}`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Reset your MoreStars password',
      html: templates.passwordResetEmail(businessName, resetUrl)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Password reset email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Password reset email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Trial Ending Reminder (3 days before)
 */
const sendTrialEndingEmail = async (email, businessName, trialEndsAt) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard`;
    const trialEndsDate = new Date(trialEndsAt).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    });

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Your MoreStars trial ends in 3 days',
      html: templates.trialEndingEmail(businessName, dashboardUrl, trialEndsDate)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Trial ending email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Trial ending email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Trial Expired Email
 */
const sendTrialExpiredEmail = async (email, businessName) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Your MoreStars trial has ended',
      html: templates.trialExpiredEmail(businessName, dashboardUrl)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Trial expired email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Trial expired email failed', { email, error: error.message });
    throw error;
  }
};


/**
 * Send Business Event Alert (for admin notifications)
 */
const sendBusinessEventAlert = async (eventType, eventData = {}) => {
  try {
    const alertEmail = process.env.BUSINESS_ALERTS_EMAIL || "kristian@kreaktive.design";
    const templates = require("./emailTemplates");
    const eventTitles = {
      new_signup: "New Account Signup",
      email_verified: "Email Verified",
      subscription_created: "New Subscription",
      subscription_cancelled: "Subscription Cancelled",
      trial_converted: "Trial Converted"
    };
    const subject = `[MoreStars] ${eventTitles[eventType] || "Business Event"}: ${eventData.businessName || eventData.email || "Unknown"}`;
    const result = await resend.emails.send({
      from: fromEmail,
      to: alertEmail,
      subject,
      html: templates.businessEventAlert(eventType, eventData)
    });
    if (result.error) throw new Error(result.error.message);
    // CRITICAL FIX: Use logger instead of console.log for proper monitoring
    logger.info("Business event alert sent", {
      eventType,
      businessName: eventData.businessName,
      email: eventData.email,
      emailId: result?.data?.id
    });
    return { success: true, emailId: result?.data?.id };
  } catch (error) {
    // CRITICAL FIX: Use logger.error instead of console.error for Sentry tracking
    logger.error("Business event alert failed", {
      eventType,
      eventData,
      error: error.message
    });
    return { success: false, error: error.message };
  }
};

/**
 * Send Admin Alert (for system notifications)
 * Does NOT throw on error - returns success: false instead
 */
const sendAdminAlert = async (title, message, stackTrace = null, metadata = {}) => {
  try {
    const adminEmail = process.env.ADMIN_EMAIL || 'admin@morestars.io';
    const templates = require('./emailTemplates');

    const result = await resend.emails.send({
      from: fromEmail,
      to: adminEmail,
      subject: `[MoreStars Alert] ${title}`,
      html: templates.adminAlertEmail(title, message, stackTrace, metadata)
    });

    if (result.error) {
      throw new Error(result.error.message);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Admin alert sent', { title, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Admin alert email failed', { title, error: error.message });
    return { success: false, error: error.message };
  }
};

/**
 * Send Support Request Email
 */
const sendSupportRequestEmail = async (email, businessName, userId, subjectType, message) => {
  try {
    const supportEmail = process.env.SUPPORT_EMAIL || 'support@morestars.io';
    const templates = require('./emailTemplates');

    const subjectLabels = {
      feature_request: 'Feature Request',
      bug_report: 'Bug Report',
      billing: 'Billing Question',
      integration: 'Integration Help',
      general: 'General Question'
    };

    const subjectLabel = subjectLabels[subjectType] || 'General Question';

    const result = await resend.emails.send({
      from: fromEmail,
      to: supportEmail,
      replyTo: email,
      subject: `[MoreStars Support] ${subjectLabel} from ${businessName}`,
      html: templates.supportRequestEmail(email, businessName, userId, subjectType, message)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Support request email sent', { email, subjectType, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Support request email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send 7-Day Trial Warning Email
 */
const sendTrialWarning7DaysEmail = async (email, businessName, trialEndsAt) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard`;
    const trialEndsDate = new Date(trialEndsAt).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    });

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: '7 days left in your MoreStars trial',
      html: templates.trialWarning7DaysEmail(businessName, dashboardUrl, trialEndsDate)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Trial 7-day warning email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Trial 7-day warning email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send 1-Day Trial Warning Email (Urgent)
 */
const sendTrialWarning1DayEmail = async (email, businessName, trialEndsAt) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard`;
    const trialEndsDate = new Date(trialEndsAt).toLocaleDateString('en-US', {
      month: 'long',
      day: 'numeric',
      year: 'numeric'
    });

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Last day of your MoreStars trial!',
      html: templates.trialWarning1DayEmail(businessName, dashboardUrl, trialEndsDate)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Trial 1-day warning email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Trial 1-day warning email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Abandoned Checkout Email
 */
const sendAbandonedCheckoutEmail = async (email, businessName) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard/subscription`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'You left something behind...',
      html: templates.abandonedCheckoutEmail(businessName, dashboardUrl)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Abandoned checkout email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Abandoned checkout email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send 30-Minute Abandoned Checkout Email
 */
const sendAbandonedCheckout30MinEmail = async (email, businessName) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard/subscription`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Still thinking it over?',
      html: templates.abandonedCheckout30MinEmail(businessName, dashboardUrl)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('30-min abandoned checkout email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('30-min abandoned checkout email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Payment Failed Email
 */
const sendPaymentFailedEmail = async (email, businessName) => {
  try {
    const templates = require('./emailTemplates');
    const dashboardUrl = `${process.env.APP_URL}/dashboard/subscription`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: 'Payment failed for your MoreStars subscription',
      html: templates.paymentFailedEmail(businessName, dashboardUrl)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Payment failed email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Payment failed email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Verification Reminder Email
 */
const sendVerificationReminderEmail = async (email, businessName, verificationToken) => {
  try {
    const templates = require('./emailTemplates');
    const verificationUrl = `${process.env.APP_URL}/verify/${verificationToken}`;

    const result = await resend.emails.send({
      from: fromEmail,
      to: email,
      subject: "Don't forget to verify your MoreStars account",
      html: templates.verificationReminderEmail(businessName, verificationUrl)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Verification reminder email sent', { email, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Verification reminder email failed', { email, error: error.message });
    throw error;
  }
};

/**
 * Send Contact Form Notification
 */
const sendContactNotification = async (formData) => {
  try {
    const supportEmail = process.env.SUPPORT_EMAIL || 'support@morestars.io';
    const templates = require('./emailTemplates');

    const topicLabels = {
      sales: 'Sales Inquiry',
      support: 'Support Request',
      billing: 'Billing Question',
      partnership: 'Partnership Opportunity',
      general: 'General Inquiry'
    };

    const topicLabel = topicLabels[formData.topic] || 'Contact Inquiry';

    const result = await resend.emails.send({
      from: fromEmail,
      to: supportEmail,
      replyTo: formData.email,
      subject: `[MoreStars Contact] ${topicLabel} from ${formData.businessName}`,
      html: templates.contactFormNotification(formData)
    });

    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message}`);
    }

    const emailId = result?.data?.id || result?.id;
    logger.info('Contact notification sent', { email: formData.email, topic: formData.topic, emailId });

    return { success: true, emailId };
  } catch (error) {
    logger.error('Contact notification email failed', { email: formData.email, error: error.message });
    throw error;
  }
};

module.exports = {
  sendNegativeFeedbackAlert,
  sendVerificationEmail,
  sendWelcomeEmail,
  sendPasswordResetEmail,
  sendTrialEndingEmail,
  sendTrialExpiredEmail,
  sendBusinessEventAlert,
  sendAdminAlert,
  sendSupportRequestEmail,
  sendTrialWarning7DaysEmail,
  sendTrialWarning1DayEmail,
  sendAbandonedCheckoutEmail,
  sendAbandonedCheckout30MinEmail,
  sendPaymentFailedEmail,
  sendVerificationReminderEmail,
  sendContactNotification
};
