require('dotenv').config();
const { Resend } = require('resend');

const resend = new Resend(process.env.RESEND_API_KEY);
const fromEmail = process.env.RESEND_FROM_EMAIL || 'onboarding@resend.dev';

const sendNegativeFeedbackAlert = async (tenantEmail, customerName, rating, comment, phone) => {
  try {
    if (!process.env.RESEND_API_KEY) {
      throw new Error('Resend API key not configured');
    }

    const subject = `⚠️ URGENT: New ${rating}-Star Review from ${customerName}`;

    const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #dc2626 0%, #991b1b 100%);
      color: white;
      padding: 30px;
      border-radius: 10px 10px 0 0;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 24px;
    }
    .content {
      background: #ffffff;
      border: 2px solid #fee2e2;
      border-top: none;
      padding: 30px;
      border-radius: 0 0 10px 10px;
    }
    .alert-box {
      background: #fef2f2;
      border-left: 4px solid #dc2626;
      padding: 15px;
      margin: 20px 0;
    }
    .customer-info {
      background: #f9fafb;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
    }
    .info-row {
      display: flex;
      margin: 10px 0;
      padding: 10px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .info-row:last-child {
      border-bottom: none;
    }
    .info-label {
      font-weight: 600;
      color: #6b7280;
      min-width: 120px;
    }
    .info-value {
      color: #111827;
    }
    .stars {
      color: #fbbf24;
      font-size: 24px;
      margin: 10px 0;
    }
    .feedback {
      background: #ffffff;
      border: 1px solid #e5e7eb;
      padding: 20px;
      border-radius: 8px;
      margin: 20px 0;
      font-style: italic;
    }
    .cta-button {
      display: inline-block;
      background: #dc2626;
      color: white;
      padding: 15px 30px;
      text-decoration: none;
      border-radius: 8px;
      font-weight: 600;
      margin: 20px 0;
    }
    .footer {
      text-align: center;
      color: #6b7280;
      font-size: 14px;
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>⚠️ URGENT: Negative Review Alert</h1>
  </div>

  <div class="content">
    <div class="alert-box">
      <strong>Action Required:</strong> A customer just left a ${rating}-star review.
      This feedback has been captured privately and was NOT posted publicly.
    </div>

    <div class="customer-info">
      <h2 style="margin-top: 0; color: #111827;">Customer Details</h2>

      <div class="info-row">
        <span class="info-label">Name:</span>
        <span class="info-value"><strong>${customerName || 'Anonymous'}</strong></span>
      </div>

      <div class="info-row">
        <span class="info-label">Phone:</span>
        <span class="info-value"><strong><a href="tel:${phone}">${phone}</a></strong></span>
      </div>

      <div class="info-row">
        <span class="info-label">Rating:</span>
        <span class="stars">${'★'.repeat(rating)}${'☆'.repeat(5 - rating)}</span>
      </div>
    </div>

    <h3 style="color: #111827;">Their Feedback:</h3>
    <div class="feedback">
      "${comment}"
    </div>

    <div style="text-align: center;">
      <a href="tel:${phone}" class="cta-button">
        📞 Call ${customerName} Now
      </a>
    </div>

    <div class="alert-box">
      <strong>💡 Recommended Action:</strong> Call this customer within 24 hours to address their concerns.
      Turning a negative experience into a positive one can create a loyal customer.
    </div>
  </div>

  <div class="footer">
    <p>This alert was generated by FilterFive</p>
    <p>The customer's review was captured privately and will not appear on public platforms.</p>
  </div>
</body>
</html>
    `;

    const result = await resend.emails.send({
      from: fromEmail,
      to: tenantEmail,
      subject: subject,
      html: htmlBody
    });

    // Debug: Log full result structure
    console.log('Resend API Response:', JSON.stringify(result, null, 2));

    // Check for errors in response
    if (result.error) {
      throw new Error(`Resend API Error: ${result.error.message} (Status: ${result.error.statusCode})`);
    }

    // Extract email ID from response
    const emailId = result?.data?.id || result?.id;

    if (!emailId) {
      throw new Error('No email ID returned from Resend API');
    }

    console.log(`✓ Negative feedback alert sent to ${tenantEmail} - Email ID: ${emailId}`);

    return {
      success: true,
      emailId: emailId
    };

  } catch (error) {
    console.error('✗ Resend email sending failed:', error.message);
    throw error;
  }
};

module.exports = {
  sendNegativeFeedbackAlert
};
